// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/consumer/consumer.proto

package consumer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionKey  int32                  `protobuf:"varint,2,opt,name=partitionKey,proto3" json:"partitionKey,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,4,opt,name=maxMessages,proto3" json:"maxMessages,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,5,opt,name=maxBytes,proto3" json:"maxBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetPartitionKey() int32 {
	if x != nil {
		return x.PartitionKey
	}
	return 0
}

func (x *ConsumeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

func (x *ConsumeRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastOffset    int64                  `protobuf:"varint,1,opt,name=lastOffset,proto3" json:"lastOffset,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeResponse) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *ConsumeResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Crc           uint32                 `protobuf:"varint,3,opt,name=crc,proto3" json:"crc,omitempty"`
	DataSize      uint32                 `protobuf:"varint,4,opt,name=dataSize,proto3" json:"dataSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *MessageHeader) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MessageHeader) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MessageHeader) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *MessageHeader) GetDataSize() uint32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_consumer_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_consumer_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_consumer_consumer_proto protoreflect.FileDescriptor

const file_proto_consumer_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/consumer/consumer.proto\x12\bconsumer\"\xa0\x01\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\"\n" +
	"\fpartitionKey\x18\x02 \x01(\x05R\fpartitionKey\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12 \n" +
	"\vmaxMessages\x18\x04 \x01(\x05R\vmaxMessages\x12\x1a\n" +
	"\bmaxBytes\x18\x05 \x01(\x05R\bmaxBytes\"`\n" +
	"\x0fConsumeResponse\x12\x1e\n" +
	"\n" +
	"lastOffset\x18\x01 \x01(\x03R\n" +
	"lastOffset\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.consumer.MessageR\bmessages\"i\n" +
	"\rMessageHeader\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03crc\x18\x03 \x01(\rR\x03crc\x12\x1a\n" +
	"\bdataSize\x18\x04 \x01(\rR\bdataSize\"N\n" +
	"\aMessage\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.consumer.MessageHeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2Y\n" +
	"\x0fConsumerService\x12F\n" +
	"\x0fconsumeMessages\x12\x18.consumer.ConsumeRequest\x1a\x19.consumer.ConsumeResponseB\x19Z\x17go-kafka/proto/consumerb\x06proto3"

var (
	file_proto_consumer_consumer_proto_rawDescOnce sync.Once
	file_proto_consumer_consumer_proto_rawDescData []byte
)

func file_proto_consumer_consumer_proto_rawDescGZIP() []byte {
	file_proto_consumer_consumer_proto_rawDescOnce.Do(func() {
		file_proto_consumer_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consumer_consumer_proto_rawDesc), len(file_proto_consumer_consumer_proto_rawDesc)))
	})
	return file_proto_consumer_consumer_proto_rawDescData
}

var file_proto_consumer_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_consumer_consumer_proto_goTypes = []any{
	(*ConsumeRequest)(nil),  // 0: consumer.ConsumeRequest
	(*ConsumeResponse)(nil), // 1: consumer.ConsumeResponse
	(*MessageHeader)(nil),   // 2: consumer.MessageHeader
	(*Message)(nil),         // 3: consumer.Message
}
var file_proto_consumer_consumer_proto_depIdxs = []int32{
	3, // 0: consumer.ConsumeResponse.messages:type_name -> consumer.Message
	2, // 1: consumer.Message.header:type_name -> consumer.MessageHeader
	0, // 2: consumer.ConsumerService.consumeMessages:input_type -> consumer.ConsumeRequest
	1, // 3: consumer.ConsumerService.consumeMessages:output_type -> consumer.ConsumeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_consumer_consumer_proto_init() }
func file_proto_consumer_consumer_proto_init() {
	if File_proto_consumer_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consumer_consumer_proto_rawDesc), len(file_proto_consumer_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consumer_consumer_proto_goTypes,
		DependencyIndexes: file_proto_consumer_consumer_proto_depIdxs,
		MessageInfos:      file_proto_consumer_consumer_proto_msgTypes,
	}.Build()
	File_proto_consumer_consumer_proto = out.File
	file_proto_consumer_consumer_proto_goTypes = nil
	file_proto_consumer_consumer_proto_depIdxs = nil
}
